// <auto-generated />
using System;
using Ban_Do_An_Vat.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Ban_Do_An_Vat.Data.MigrationsPostgres
{
    [DbContext(typeof(ApplicationDbContextPostgres))]
    [Migration("20260816182453_AddImageDataToPostgres")]
    partial class AddImageDataToPostgres
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ban_Do_An_Vat.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            AccessFailedCount = 0,
                            Address = "123 Đường ăn vặt, Sài Gòn",
                            ConcurrencyStamp = "2dab26c7-0e14-438c-94e9-14581e0a3f72",
                            Email = "admin@bandoanvat.com",
                            EmailConfirmed = true,
                            FullName = "Hệ thống Munchies",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@BANDOANVAT.COM",
                            NormalizedUserName = "ADMIN@BANDOANVAT.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAED8KYW4KNhCMq9bok9REwxKsUzYP/rvZQMGwG8rIcuaeFDgjkymGPjmOEt/Gaudx6Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "admin@bandoanvat.com"
                        });
                });

            modelBuilder.Entity("Ban_Do_An_Vat.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ImageContentType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<byte[]>("ImageData")
                        .HasColumnType("bytea");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Các loại bánh tráng trộn, bánh tráng cuộn, khô bò, khô gà lá chanh đậm đà hương vị Việt",
                            ImageUrl = "https://images.unsplash.com/photo-1599599810769-bcde5a160d32?q=80&w=600&auto=format&fit=crop",
                            Name = "Bánh Tráng & Khô"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Hạt điều rang muối, hạt dẻ, mít sấy, trái cây sấy giòn tự nhiên thơm ngon, bổ dưỡng",
                            ImageUrl = "https://images.unsplash.com/photo-1596560548464-f010689b7f1e?q=80&w=600&auto=format&fit=crop",
                            Name = "Hạt & Trái Cây Sấy"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Bánh gấu nhân kem, kẹo dẻo trái cây, bánh quy ngọt ngào ăn vặt vui miệng",
                            ImageUrl = "https://images.unsplash.com/photo-1505252585461-04db1ebb846d?q=80&w=600&auto=format&fit=crop",
                            Name = "Bánh & Kẹo Ngọt"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Rong biển cháy tỏi, khoai tây lắc phô mai, các món ăn vặt trào lưu mới",
                            ImageUrl = "https://images.unsplash.com/photo-1613919113640-25732ec5e61f?q=80&w=600&auto=format&fit=crop",
                            Name = "Ăn Vặt Hiện Đại"
                        });
                });

            modelBuilder.Entity("Ban_Do_An_Vat.Models.Combo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ImageContentType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<byte[]>("ImageData")
                        .HasColumnType("bytea");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<decimal>("OriginalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SalePrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Combos");
                });

            modelBuilder.Entity("Ban_Do_An_Vat.Models.ComboItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ComboId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("SnackId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ComboId");

                    b.HasIndex("SnackId");

                    b.ToTable("ComboItems");
                });

            modelBuilder.Entity("Ban_Do_An_Vat.Models.Coupon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DiscountType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<decimal>("MinOrderAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Coupons");
                });

            modelBuilder.Entity("Ban_Do_An_Vat.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CouponCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("DeliveryAddress")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OrderNotes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Ban_Do_An_Vat.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ComboId")
                        .HasColumnType("integer");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int?>("SnackId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ComboId");

                    b.HasIndex("OrderId");

                    b.HasIndex("SnackId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Ban_Do_An_Vat.Models.Snack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ImageContentType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<byte[]>("ImageData")
                        .HasColumnType("bytea");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Ingredients")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("Rating")
                        .HasColumnType("double precision");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer");

                    b.Property<string>("Weight")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Snacks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Bánh tráng sợi dai mềm trộn cùng sa tế tôm cay nồng, khô bò sợi, tép khô rang, hành phi thơm lừng, xoài xanh bào và rau răm tươi mát. Hương vị đường phố đích thực.",
                            ImageUrl = "https://images.unsplash.com/photo-1626132647523-66f5bf380027?q=80&w=600&auto=format&fit=crop",
                            Ingredients = "Bánh tráng, sa tế, khô bò, tép rang, xoài xanh, rau răm, nước sốt tắc",
                            IsAvailable = true,
                            Name = "Bánh Tráng Trộn Sài Gòn",
                            Price = 25000m,
                            Rating = 4.7999999999999998,
                            StockQuantity = 100,
                            Weight = "150g"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Thịt bò tươi ngon chọn lọc được tẩm ướp đậm đà với sả băm, tỏi, ớt hiểm cay nồng và mật ong tự nhiên. Sấy khô vừa phải giữ độ mềm ngọt của từng sớ thịt.",
                            ImageUrl = "https://images.unsplash.com/photo-1529042410759-befb1204b468?q=80&w=600&auto=format&fit=crop",
                            Ingredients = "Thịt bò tươi, sả, tỏi, ớt hiểm, mật ong, ngũ vị hương",
                            IsAvailable = true,
                            Name = "Khô Bò Xé Sợi Cay Tè",
                            Price = 89000m,
                            Rating = 4.9000000000000004,
                            StockQuantity = 50,
                            Weight = "180g"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Ức gà xé tơi giòn rụm kết hợp với lá chanh tươi thái sợi sấy thơm, tỏi phi vàng và ớt khô nguyên quả. Vị mặn ngọt hài hòa, cay thơm dịu nhẹ khó cưỡng.",
                            ImageUrl = "https://images.unsplash.com/photo-1608039755401-742074f0548d?q=80&w=600&auto=format&fit=crop",
                            Ingredients = "Thịt gà, lá chanh, tỏi phi, ớt khô, gia vị, nước mắm",
                            IsAvailable = true,
                            Name = "Khô Gà Lá Chanh Giòn Cay",
                            Price = 45000m,
                            Rating = 4.7000000000000002,
                            StockQuantity = 150,
                            Weight = "150g"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "Cơm cháy đáy nồi giòn tan rụm lót lớp chà bông heo (ruốc) dày đặc, rưới thêm nước sốt mắm ớt hành kẹo kẹo thơm lừng, béo ngậy.",
                            ImageUrl = "https://images.unsplash.com/photo-1568254183919-78a4f43a2877?q=80&w=600&auto=format&fit=crop",
                            Ingredients = "Nếp thơm, chà bông heo sạch, nước sốt mắm ớt, hành lá",
                            IsAvailable = true,
                            Name = "Cơm Cháy Siêu Ruốc (Chà Bông)",
                            Price = 39000m,
                            Rating = 4.5999999999999996,
                            StockQuantity = 80,
                            Weight = "250g"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Description = "Hạt điều loại A hạt to tròn béo bùi nguyên hạt, rang củi thủ công cùng muối tinh giữ nguyên lớp vỏ lụa giúp giữ vị ngọt thanh tự nhiên và độ giòn tan lâu hơn.",
                            ImageUrl = "https://images.unsplash.com/photo-1509440159596-0249088772ff?q=80&w=600&auto=format&fit=crop",
                            Ingredients = "Hạt điều vỏ lụa Bình Phước, muối tinh 1%",
                            IsAvailable = true,
                            Name = "Hạt Điều Vỏ Lụa Rang Muối Bình Phước",
                            Price = 95000m,
                            Rating = 4.7999999999999998,
                            StockQuantity = 60,
                            Weight = "250g"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Description = "Mít chín cây tươi ngon được sấy nhiệt hiện đại giúp giữ nguyên màu vàng óng, mùi thơm đặc trưng và vị ngọt đậm tự nhiên. Giòn rụm không bị gắt dầu.",
                            ImageUrl = "https://images.unsplash.com/photo-1600850756094-8ab05e2ed88a?q=80&w=600&auto=format&fit=crop",
                            Ingredients = "Mít tươi, dầu cọ thực vật sấy",
                            IsAvailable = true,
                            Name = "Mít Sấy Giòn Xuất Khẩu",
                            Price = 42000m,
                            Rating = 4.5,
                            StockQuantity = 120,
                            Weight = "150g"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            Description = "Vỏ bánh giòn xốp tạo hình chú gấu dễ thương ôm trọn nhân kem sữa béo ngậy ngọt ngào bên trong. Món ăn gắn liền với tuổi thơ bao thế hệ.",
                            ImageUrl = "https://images.unsplash.com/photo-1558961309-dbdf7177e419?q=80&w=600&auto=format&fit=crop",
                            Ingredients = "Bột mì, sữa bột, đường cát, bơ thực vật, hương sữa tổng hợp",
                            IsAvailable = true,
                            Name = "Bánh Gấu Nhân Kem Sữa Béo",
                            Price = 30000m,
                            Rating = 4.7000000000000002,
                            StockQuantity = 200,
                            Weight = "200g"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 4,
                            Description = "Lá rong biển khô tẩm gia vị muối ớt cay mặn, sấy giòn rụm rồi phi thơm cùng tỏi băm ngập dầu vàng giòn. Thích hợp cho người ăn kiêng thanh đạm.",
                            ImageUrl = "https://images.unsplash.com/photo-1607349913338-fca6f7fc42d0?q=80&w=600&auto=format&fit=crop",
                            Ingredients = "Rong biển nhập khẩu, tỏi phi giòn, muối, ớt, đường",
                            IsAvailable = true,
                            Name = "Rong Biển Cháy Tỏi Giòn Tan",
                            Price = 35000m,
                            Rating = 4.7999999999999998,
                            StockQuantity = 90,
                            Weight = "90g"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "2",
                            Name = "Customer",
                            NormalizedName = "CUSTOMER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "1",
                            RoleId = "1"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Ban_Do_An_Vat.Models.ComboItem", b =>
                {
                    b.HasOne("Ban_Do_An_Vat.Models.Combo", "Combo")
                        .WithMany("ComboItems")
                        .HasForeignKey("ComboId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ban_Do_An_Vat.Models.Snack", "Snack")
                        .WithMany()
                        .HasForeignKey("SnackId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Combo");

                    b.Navigation("Snack");
                });

            modelBuilder.Entity("Ban_Do_An_Vat.Models.OrderItem", b =>
                {
                    b.HasOne("Ban_Do_An_Vat.Models.Combo", "Combo")
                        .WithMany()
                        .HasForeignKey("ComboId");

                    b.HasOne("Ban_Do_An_Vat.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ban_Do_An_Vat.Models.Snack", "Snack")
                        .WithMany()
                        .HasForeignKey("SnackId");

                    b.Navigation("Combo");

                    b.Navigation("Order");

                    b.Navigation("Snack");
                });

            modelBuilder.Entity("Ban_Do_An_Vat.Models.Snack", b =>
                {
                    b.HasOne("Ban_Do_An_Vat.Models.Category", "Category")
                        .WithMany("Snacks")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Ban_Do_An_Vat.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Ban_Do_An_Vat.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ban_Do_An_Vat.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Ban_Do_An_Vat.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ban_Do_An_Vat.Models.Category", b =>
                {
                    b.Navigation("Snacks");
                });

            modelBuilder.Entity("Ban_Do_An_Vat.Models.Combo", b =>
                {
                    b.Navigation("ComboItems");
                });

            modelBuilder.Entity("Ban_Do_An_Vat.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
